### PR TITLE
Added anticheat config

### LINKED ISSUE #263: Ability to disable server-side anticheat via config.json
# Feature Request
Allow hosts to disable server-side anticheat via config.json
## Feature Information:

Disables server-side anticheat with a true/false boolean in config.json

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

### PR DESCRIPTION
**Pull request by XtraCube**
### Closes issues

- closes #263

### CODE REVIEW

**Comment by Elsensee** [comment]
You're change only removes the kicking after a cheat was detected. So, this is even worse behaviour since the packets won't be sent to the other players but they'll stop at the server. You need to prevent every throw before it happens, since it'll disrupt the program flow.

**Comment by AeonLucid** [comment]
This is not the way, sorry.

**Comment by js6pak** [comment]
Wtf is with these spaces

**Comment by js6pak** [comment]
And its duplicate of #117 and #274

**Pull request closed without merging**
