### PR TITLE
Send game options to single player

### PR DESCRIPTION
**Pull request by AlexejheroYTB**
### Description

Adds `SendSettingsToAsync`, to send settings only to a single player.

### Closes issues

- closes #101

### CODE REVIEW

**Comment by AeonLucid** [comment]
Nice PR but I'm not sure about this. Wouldn't it be better if you could specify your own instance of the game options so you do not need to modify the global one of the server?

**Comment by AlexejheroYTB** [comment]
So a GameOptionsData parameter?

**Comment by AeonLucid** [comment]
Yeah correct

**Comment by AlexejheroYTB** [comment]
Closing this for now, I will add something similar in a following PR based on #158.

**Pull request closed without merging**
