### PR TITLE
Optional different Region Name for web file generator

### LINKED ISSUE #207: Change region name
# Feature Request

## Feature Information:

I noticed, that it is possible to change the region name in the regionInfo.dat file to any 8 characters. If this is not a limit by the game but by the server, could this be changed to support other name lengths as well?
## I confirm:
- [x] that I have searched for an existing feature request matching the description.

### PR DESCRIPTION
**Pull request by crazychatting**
### Description

Just a little more shiny form, added possibility to change region name.
Some little fixes with footer positioning for IE11 and fixed project URL to github.

### Closes issues

Closes #207

### CODE REVIEW

**Comment by crazychatting** [comment]
I don´t know how to link the issue #207 wit this PR so that it will be listed on the right side in "Linked issues"...

**Comment by dimaguy** [comment]
"Closes #207"

**Comment by crazychatting** [comment]
> "Closes #207" in the PR description (with C not c)

tried, but doesn´t work either. I had a look into other PRs, they also just have "c"

**Comment by js6pak** [comment]
It doesn't close #207 tho, it was about winforms patcher not github page or cli patcher

**Comment by crazychatting** [comment]
fair enough

**Comment by js6pak** [comment]
Implemented in be41fd043f207fc14d874b9072da3e6613a50b74

**Pull request closed without merging**
