### PR TITLE
Implemented AntiCheatConfig.Enable

### LINKED ISSUE #263: Ability to disable server-side anticheat via config.json
# Feature Request
Allow hosts to disable server-side anticheat via config.json
## Feature Information:

Disables server-side anticheat with a true/false boolean in config.json

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

### PR DESCRIPTION
**Pull request by zokradonh**
### Description
Implementing configuration option to enable/disable AntiCheat checks.

Open points:

- [ ] Check if there are any security implications(in the meaning of hacking not cheating) by not validating data
- [ ] Successful tests with my friends
- [ ] Add to documentation

### Closes issues
- closes #263

### CODE REVIEW

**Comment by dimaguy** [comment]
Have you confirmed that there isnt a denied PR with your changes?

**Comment by zokradonh** [comment]
There are a lot of PRs trying to implement AntiCheat disable options, but they were all rejected because they are bad implemented.

This implementation is using dependency injection design pattern like everything else in this project.

**Comment by dimaguy** [comment]
I dont think your approach is much better, as Ive seen a similar one denied

**Comment by zokradonh** [comment]
There is no similar one that has been denied.

**Comment by js6pak** [comment]
Dima is wrong as always, other anticheat prs were denied because they weren't stopping impostorcheatexception from throwing thus causing side effects, while this PR in theory works it still wraps exceptions in ifs, when exceptions shouldn't be used in anticheat in the first place.

**Comment by zokradonh** [comment]
I agree that cheating shouldn't cause exceptions. One could discuss about introducing an AntiCheatService that handles related stuff.

But I will not fix this flaw in the codebase of this project. My contribution ends here. This community is too toxic for any good team work. This is not the IT professional communication I am used to.

**Comment by Phoenix616** [comment]
Any ETA when this or a similar option is going to get pulled? Being able to disable (some parts) of the anti cheat is essential to get certain mod functions to work on this server.

**Comment by benniii1337** [comment]
My lobby does use this already to play the extra role mod, so i can confirm that it does work and the engineer doesn't get banned for venting.

We only got one problem, but that could be complety unrelated: First round on a new map players will be kicked if they try to open a door, or some other interactables. After reconnecting and starting a fresh round we don't have that problem anymore.

**Comment by ballaual** [comment]
> My lobby does use this already to play the extra role mod, so i can confirm that it does work and the engineer doesn't get banned for venting.
> 
> We only got one problem, but that could be complety unrelated: First round on a new map players will be kicked if they try to open a door, or some other interactables. After reconnecting and starting a fresh round we don't have that problem anymore.
> 
> Update: It seem it was related, my old statement was without the bugfix from 2 days ago. We just played some rounds with it and it did work this time without any problems.

can you explain for any noobies out here what to do and how to get it running on a impostor server until it is actually not implemented into the mod?

**Comment by ballaual** [comment]
> My lobby does use this already to play the extra role mod, so i can confirm that it does work and the engineer doesn't get banned for venting.
> 
> We only got one problem, but that could be complety unrelated: First round on a new map players will be kicked if they try to open a door, or some other interactables. After reconnecting and starting a fresh round we don't have that problem anymore.
> 
> Update: It seem it was related, my old statement was without the bugfix from 2 days ago. We just played some rounds with it and it did work this time without any problems.

could you show the noobies (me included ^^) how to get this running?

**Comment by benniii1337** [comment]
> could you show the noobies (me included ^^) how to get this running?

Sorry, im not into it myself. A friend of mine did this. Theoretically you have to merge this changes with the source files and have to compile it for yourself. I guess. Maybe someone can give a better explanation. Otherwise you have to wait for the next Impostor update, which i hope will include this.

**Comment by JuliusFo** [comment]
You just have to download the latest source code and compile it with something like Microsoft Visual Studio :).

**Comment by Phoenix616** [comment]
> could you show the noobies (me included ^^) how to get this running?

You can just build and run it with docker and buildx. Clone their repo with git, switch to the branch and run `docker buildx`.

(Alternatively you can use docker compose. Build it with `DOCKER_BUILDKIT=1 docker-compose` and this [docker-compose.yml](https://gist.github.com/Phoenix616/a7a40d9c7c626bcce90428905a5138d5))

**Comment by ballaual** [comment]
> You just have to download the latest source code and compile it with something like Microsoft Visual Studio :).
> 
> 1. Open the solution file Impostor.sln with Visual Studio
> 2. Hit the "Build -> Build Solution" button inside the main menu
> 3. Navigate to the following path inside the source code dir: "\bin\Debug\net5.0"
> 4. Copy the files to a seperate folder or start the imposter.exe from there
> 
> Have fun :)

that would work if you run a server local, right? but i want to run that on a linux (debian) machine

**Comment by zokradonh** [comment]
Closing in favor of #327

**Pull request closed without merging**
