### PR TITLE
Fix cheating disconnect message

### PR DESCRIPTION
**Pull request by js6pak**
DisconnectReason.Hacking has been broken in base game for a long time so replace it with a custom message. Also add a random support code for easier debugging in case of false positives.

Current:
image

This PR:
image

### CODE REVIEW

**Comment by NikoCat233** [comment]
the problem is this disconnect message is always shown as kicked to other players

**Comment by NikoCat233** [comment]
public async ValueTask RemoveAsync(DisconnectReason reason, string custom = "")
        {
            await Game.HandleRemovePlayer(Client.Id, reason);
            await Client.DisconnectAsync(reason, custom);
        }

**Comment by js6pak** [comment]
For the disconnect notification shown to other players we've got just these 4 options. Ideally we'd use Banned/Kicked but those specify the host as the one who bans/kicks so it doesn't really make sense for us.

> the problem is this disconnect message is always shown as kicked to other players

Currently, the "left the game" message is shown, so I don't really know what you mean?

`DisconnectReason.ExitGame` (the default in Impostor)
image

`DisconnectReason.Banned`
image

`DisconnectReason.Kicked`
image

any other `DisconnectReason`
image

**Review by miniduikboot — APPROVED** [review]
lgtm

**Comment by NikoCat233** [comment]
image
I cant replicate what you have shown in your pictures

**Comment by js6pak** [comment]
> If a player is kicked by Impostor for anticheat purpose
	I expect server telling others that "It is banned by AntiCheat", not "It exited the game itself"

As far as I know, those 4 messages I mentioned are the only ones we can use on vanilla so that wouldn't be possible.

> Also for other DisconnectReasons like custom "Reliable packet was ****"
	We should also tell others the correct Disconnect Reasons instead of the deafult ExitGame

We could indeed use the "left the game due to error" for those, but that would be a different PR.

> Currently My region is using this function to broadcast correct Disconnect Messages to other players

Are you sure that's the case on vanilla clients? Can you show a disconnect notification message different from the ones I mentioned?

**Comment by NikoCat233** [comment]
My opinion is we should send the exact disconnect reasons to everyone like innersloth does
no matter what clients can actually see

**Pull request merged**
