### PR TITLE
Add movement api

### LINKED ISSUE #116: Add spawn positions for players depending on which map to API event
The Skeld
(-2.1, 2.75), (-1.8, 2.9), (-1.47, 3), (-1.15, 3.12), (-0.82, 3.25), (0.94, 3.25), (1.25, 3.12), (1.57, 3), (1.9, 2.9), (2.2, 2.75)
MIRA HQ
(-2.1, 2.75), (-1.8, 2.9), (-1.47, 3), (-1.15, 3.12), (-0.82, 3.25), (0.94, 3.25), (1.25, 3.12), (1.57, 3), (1.9, 2.9), (2.2, 2.75)
Polus
(-2.1, 2.75), (-1.8, 2.9), (-1.47, 3), (-1.15, 3.12), (-0.82, 3.25), (0.94, 3.25), (1.25, 3.12), (1.57, 3), (1.9, 2.9), (2.2, 2.75)

### LINKED ISSUE #167: Is there a way to get the player current position on the map?
I was trying to do a plugin that changes a player position with other player
I was able to change the player position with player.Character.NetworkTransform.SnapToAsync(newPosition), but I wanted to know if it is possible to know all the players position at a given time, something like this:

public void OnGameStarted(IGameStartedEvent e)
{
  _logger.LogInformation($"Game is starting.");

  foreach (var player in e.Game.Players)
    {
       _logger.LogInformation($"{player.Character.NetworkTransform.CurrentPlayerPosition}") // here we know the player position
     }
}

Also, I did not see how people get the Map coordinates limits (like, in Skeld which coordinates the Admin/Cafeteria is, something like that). Does anyone know that?

Also, is there a way to allow the chat use during the game phase (not only in the discussion phase)? So the users can type a message like:
/teleport (2.5, -1.53)
and be teleported to that location (using the message listener).

Anyway, thanks for the attention. Great Api!

### PR DESCRIPTION
**Pull request by js6pak**
### Description

- Makes Deserialize/Serialize of components async
- Implements poolable `IPlayerMovementEvent`
- Adds `Position` to `IInnerCustomNetworkTransform`
- Closes #116
- Closes #167

### CODE REVIEW

**Comment by LorenzoPapi** [comment]
The position in the map isn't updated when the game starts, it remains as the lobby one

**Comment by ZiadMontaser** [comment]
can you calculate the position when game starts because it reamains the same as lobby if player didnt send movment bucket

**Comment by js6pak** [comment]
*just read the last line of the description*

**Comment by LorenzoPapi** [comment]
I confirm that this movement api works fine, no issues found, the position is the right one for both the client and the server, no sync problems found.

**Comment by SushiBtw** [comment]
Can confirm that it works fine, everything is synced up per me. No issues.

**Comment by danbudworthmead** [comment]
Add private Vector2 _lastSyncPosition; 
Whenever _targetSyncPosition is set, update _lastSyncPosition just before.

This will make it easier to do anti-cheat for wall hacking etc.

If a player moves to an invalid location, ping them back to _lastSyncPosition.

**Comment by Sanae6** [comment]
Bump 🙃 why is there a stale bot when the repo is dead @AeonLucid

**Comment by JohnTranQUT** [comment]
Was this into the latest version?

**Pull request closed without merging**
