### PR TITLE
Feature/gamemanager improvement

### PR DESCRIPTION
**Pull request by JKamsker**
- Retry code creation
- Async Node Lookup

### CODE REVIEW

**Comment by AeonLucid** [comment]
Please change:
- NodeLocatorExtensions.NodeExistsAsync > ExistsAsync
- Weird `using` changes
- I'm not sure how I feel about having a normal and an async node locator, I'd prefer if you just updated the existing node locator

**Comment by JKamsker** [comment]
> Please change:
> 
> * NodeLocatorExtensions.NodeExistsAsync > ExistsAsync
> * Weird `using` changes
> * I'm not sure how I feel about having a normal and an async node locator, I'd prefer if you just updated the existing node locator

All fixed.
Usings: Sry, my autoformat was misconfigured 😅 
Node locator: Me neither, i just didnt want to break too much things 😅

**Comment by AeonLucid** [comment]
Awesome, the submodule is still there though

**Comment by JKamsker** [comment]
@AeonLucid ahh thanks, didnt catch that 🙈

**Comment by AeonLucid** [comment]
Thanks!

**Pull request merged**
