### PR TITLE
Support LobbyBehaviour Rpc calls

### PR DESCRIPTION
**Pull request by NikoCat233**
LobbyTimeExpiring is used in vanilla servers to broadcast room closing messages. Maybe some plugins can use it to close rooms.
ExtendLobbyTimer seems never used but it exists in code to cancel LobbyTimeExpiring.

### CODE REVIEW

**Comment by Pietrodjaowjao** [comment]
Man, if its gonna be used in plugins atleast make It not useless

**Comment by NikoCat233** [comment]
Should be more like a anticheat improvement
You can spam this and make very awesome noises

**Comment by miniduikboot** [comment]
Hey Niko, I'm trying to clean up PR's that we ignored while we were busy with merging a basic version of 6.18 support. Are you still interested in this PR? If yes, please rebase it on top of master

**Comment by NikoCat233** [comment]
ok

**Pull request closed without merging**
